name 'tdd-chef-docker'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures tdd-chef-docker'
long_description 'Installs/Configures tdd-chef-docker'
version '0.1.0'
